services:
  museu-app:
    build:
      context: ../../..
    image: museu_de_fisica:v2
    hostname: app.museu.fisica
    container_name: app-museu-fisica-cnt
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://museu-postgresql:5432/museu
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://museu-postgresql:5432/museu
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080

  museu-postgresql:
    image: docker.io/library/postgres:13.2
    hostname: db.museu.fisica
    container_name: db-museu-fisica-cnt
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=museu
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5433:5432

volumes:
  postgres_data: {}
